parameters:
    env(ELASTICSEARCH_HOSTS): 'localhost'
    env(DOCUMENT_PATH): '/documents/'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $documentPath: '%env(string:DOCUMENT_PATH)%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Elasticsearch\ClientBuilder:
        factory: ['Elasticsearch\ClientBuilder', create]
        calls:
            - [setHosts, [['%env(string:ELASTICSEARCH_HOSTS)%']]]

    Elasticsearch\Client:
        factory: ['@Elasticsearch\ClientBuilder', build]
